### ISSUE TITLE
is this project working?

### ISSUE THREAD

**Issue by grmkris** [hendisantika/spring-boot-angular-fileupload#1]
Hello I've been trying to implement something similar to your project and I was using it as a reference. I haven't tried running it yet, but I think some of your methods are not implemented yet. 
DocumentServiceImpl has documentDao.findOne(id) 
and findOne() function is not yet implemented.

**Comment by hendisantika** [comment]
Hello @grmkris, this project is working fine on my local.
You can Pull Request for that If you want to add more feature to this repo. Maybe I miss that @grmkris.

This is very simple.

**Comment by grmkris** [comment]
I did pull request and yes it is actually working. I am doing something wrong on my project.
sorry

**Comment by hendisantika** [comment]
OK. I will close the issue then.
